--------------------------------------------------------
--  已建立檔案 - 星期五-八月-26-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BUILD_ORDER
--------------------------------------------------------

  CREATE TABLE "SSD"."BUILD_ORDER" 
   (	"USER_ID" NUMBER(5,0), 
	"ORDER_NUMBER" VARCHAR2(12 BYTE), 
	"REMARK" VARCHAR2(1600 BYTE), 
	"ITEM_INFORMATION" VARCHAR2(350 BYTE), 
	"DEADLINE" DATE, 
	"BUILD_TIME" DATE, 
	"BUILD_STATE" VARCHAR2(32 BYTE), 
	"PICTURE" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CASH_LOG
--------------------------------------------------------

  CREATE TABLE "SSD"."CASH_LOG" 
   (	"USER_ID" NUMBER(5,0), 
	"LOG_NUMBER" VARCHAR2(12 BYTE), 
	"TIME" DATE, 
	"MONEY" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ITEM_INFORMATION
--------------------------------------------------------

  CREATE TABLE "SSD"."ITEM_INFORMATION" 
   (	"USER_ID" NUMBER(5,0), 
	"NAME" VARCHAR2(80 BYTE), 
	"ITEM_NUMBER" VARCHAR2(12 BYTE), 
	"ORDER_NUMBER" VARCHAR2(12 BYTE), 
	"MAX" NUMBER(3,0), 
	"MIN" NUMBER(3,0), 
	"MONEY" NUMBER(4,0), 
	"SUGER" VARCHAR2(10 BYTE), 
	"ICE" VARCHAR2(10 BYTE), 
	"SIZE" VARCHAR2(10 BYTE), 
	"BIG_PRICE" NUMBER(4,0), 
	"MID_PRICE" NUMBER(4,0), 
	"SMALL_PRICE" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JOIN_ORDER
--------------------------------------------------------

  CREATE TABLE "SSD"."JOIN_ORDER" 
   (	"JOIN_LOG" VARCHAR2(12 BYTE), 
	"ORDER_NUMBER" VARCHAR2(12 BYTE), 
	"ITEM_NUMBER" VARCHAR2(12 BYTE), 
	"COUNT" NUMBER(4,0), 
	"JOIN_TIME" DATE, 
	"GET" NUMBER(1,0), 
	"USER_ID" NUMBER(5,0), 
	"MONEY" NUMBER(7,0), 
	"SIZE" VARCHAR2(10 BYTE), 
	"SUGER" VARCHAR2(10 BYTE), 
	"ICE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_DATA
--------------------------------------------------------

  CREATE TABLE "SSD"."USER_DATA" 
   (	"USER_ID" NUMBER(5,0), 
	"ACCOUNT" VARCHAR2(60 BYTE), 
	"PASSWORD" VARCHAR2(60 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"PHONE" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(320 BYTE), 
	"MONEY" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SSD.BUILD_ORDER
SET DEFINE OFF;
Insert into SSD.BUILD_ORDER (USER_ID,ORDER_NUMBER,REMARK,ITEM_INFORMATION,DEADLINE,BUILD_TIME,BUILD_STATE,PICTURE) values (1,'8','創立「清心冷飲站」
　　1987年3月8日，趙福全夫妻於台南市南區金華路二段巷弄內，創立「清心冷飲站」，設置一座簡易的吧檯，陳列茶桶、冰櫥、糖罐、杯子等器具，對外販售冷飲、冰品。其中「茶飲」最受消費者的青睞，當日燜煮新鮮且濃厚的熱茶汁，結合清透的衛生冰塊，加入適量的糖水，以調酒杯現場手工沖泡、調製，幻化成風味獨特的茶飲，提供消費者即時、沁涼的外帶飲品。而剛由調酒杯倒入飲用杯中的茶飲，茶湯上層漂浮
首創「烏龍綠茶」
　　茶葉無疑是茶飲的首要元素，趙福全先生經營「清心冷飲站」以來，不僅嚴選優質茶葉以製作茶飲，更多方試茶、品茶、評茶、配茶，精進沖泡、調製技術，參酌顧客回饋意見，以研發更多符合消費者口味的茶飲。1988年6月，成功推出台灣首創「烏龍綠茶」，澄澈的黃褐色茶湯，入口清新芳香、甘醇渾厚，微帶炭燒味，回甘則馥郁而綿長','清新福全',to_date('31-12月-16','DD-MON-RR'),to_date('10-6月 -16','DD-MON-RR'),'live','1233.jpg');
Insert into SSD.BUILD_ORDER (USER_ID,ORDER_NUMBER,REMARK,ITEM_INFORMATION,DEADLINE,BUILD_TIME,BUILD_STATE,PICTURE) values (1,'4','派克🐔排不稀奇，但對流浪他鄉的遊子們可以吃到家鄉味，這可是一大件事 。

之前在台中就有吃過，印象是多汁帶點甜味，生為一個什麼食物都要加糖的台南人來說我是挺喜歡的，何況是在澳洲！一定要來試一下的!!

剛進店時還沒很多人，但我們開始吃的時候就客滿了。幾乎都是華人居多（因為開在china town 嘛），其實也有看到幾個澳洲人在外面偷看但不敢走進來。
下面是Menu
對，你沒有看錯！','派克雞排',to_date('12-6月 -16','DD-MON-RR'),to_date('08-6月 -16','DD-MON-RR'),'live','c4004.jpg');
Insert into SSD.BUILD_ORDER (USER_ID,ORDER_NUMBER,REMARK,ITEM_INFORMATION,DEADLINE,BUILD_TIME,BUILD_STATE,PICTURE) values (1,'5','創立「清心冷飲站」
　　1987年3月8日，趙福全夫妻於台南市南區金華路二段巷弄內，創立「清心冷飲站」，設置一座簡易的吧檯，陳列茶桶、冰櫥、糖罐、杯子等器具，對外販售冷飲、冰品。其中「茶飲」最受消費者的青睞，當日燜煮新鮮且濃厚的熱茶汁，結合清透的衛生冰塊，加入適量的糖水，以調酒杯現場手工沖泡、調製，幻化成風味獨特的茶飲，提供消費者即時、沁涼的外帶飲品。而剛由調酒杯倒入飲用杯中的茶飲，茶湯上層漂浮
首創「烏龍綠茶」
　　茶葉無疑是茶飲的首要元素，趙福全先生經營「清心冷飲站」以來，不僅嚴選優質茶葉以製作茶飲，更多方試茶、品茶、評茶、配茶，精進沖泡、調製技術，參酌顧客回饋意見，以研發更多符合消費者口味的茶飲。1988年6月，成功推出台灣首創「烏龍綠茶」，澄澈的黃褐色茶湯，入口清新芳香、甘醇渾厚，微帶炭燒味，回甘則馥郁而綿長','清新福全',to_date('26-6月 -16','DD-MON-RR'),to_date('08-6月 -16','DD-MON-RR'),'live','images.jpg');
Insert into SSD.BUILD_ORDER (USER_ID,ORDER_NUMBER,REMARK,ITEM_INFORMATION,DEADLINE,BUILD_TIME,BUILD_STATE,PICTURE) values (1,'2','宅配說明﻿
本公司與統一速達黑貓宅急便合作低溫宅配
請在結帳時【備註欄】填寫送達時段、希望到達日(自訂單日起不得小於4天、大於10天)。
訂單成立7~10天內將為您完成出貨；商城系統為保障消費者權益，因此訂單商品不得逾期出貨，敬請見諒。
黑貓提供時段性送達服務，無法在指定精準時間送達(例如：指定AM9:05精準送達)。
配達時段可選擇為：上午(8:00~12:00)、下午(12:00~1','Black As C',to_date('13-6月 -16','DD-MON-RR'),to_date('08-6月 -16','DD-MON-RR'),'live','124472.jpg');
Insert into SSD.BUILD_ORDER (USER_ID,ORDER_NUMBER,REMARK,ITEM_INFORMATION,DEADLINE,BUILD_TIME,BUILD_STATE,PICTURE) values (1,'3','千呼萬喚使出來之店內menu終於與大家見面拉！！
第一版本的menu是我們精心為各位用餐者所精選調配的，同時、更維持不變的精神：要健康更要好吃！
請大家品嚐後務必多多指教，讓左先生的西式廚房能做出您最滿意的餐點喔
就是明天！Mr.Tsuo左先生的西式廚房正式開幕！
謝謝各界朋友一直以來不吝嗇的指導，希望明天大家都會有個愉快滿意的用餐經驗喔。
PS: Mr.Tsuo左先生的西式廚房也','MR. TSUO ',to_date('14-6月 -16','DD-MON-RR'),to_date('08-6月 -16','DD-MON-RR'),'live','123676.jpg');
Insert into SSD.BUILD_ORDER (USER_ID,ORDER_NUMBER,REMARK,ITEM_INFORMATION,DEADLINE,BUILD_TIME,BUILD_STATE,PICTURE) values (1,'6','lkedjlkasjdlasdjlasd','默切義大利麵',to_date('10-6月 -16','DD-MON-RR'),to_date('08-6月 -16','DD-MON-RR'),'live','122203.jpg');
Insert into SSD.BUILD_ORDER (USER_ID,ORDER_NUMBER,REMARK,ITEM_INFORMATION,DEADLINE,BUILD_TIME,BUILD_STATE,PICTURE) values (1,'7','lksdjklsdjflsdf','好喝咖啡',to_date('08-6月 -16','DD-MON-RR'),to_date('08-6月 -16','DD-MON-RR'),'live','1233.jpg');
Insert into SSD.BUILD_ORDER (USER_ID,ORDER_NUMBER,REMARK,ITEM_INFORMATION,DEADLINE,BUILD_TIME,BUILD_STATE,PICTURE) values (1,'9','宅配說明﻿
本公司與統一速達黑貓宅急便合作低溫宅配
請在結帳時【備註欄】填寫送達時段、希望到達日(自訂單日起不得小於4天、大於10天)。
訂單成立7~10天內將為您完成出貨；商城系統為保障消費者權益，因此訂單商品不得逾期出貨，敬請見諒。
黑貓提供時段性送達服務，無法在指定精準時間送達(例如：指定AM9:05精準送達)。
配達時段可選擇為：上午(8:00~12:00)、下午(12:00~1','Black As C',to_date('31-12月-16','DD-MON-RR'),to_date('10-6月 -16','DD-MON-RR'),'live','122203.jpg');
Insert into SSD.BUILD_ORDER (USER_ID,ORDER_NUMBER,REMARK,ITEM_INFORMATION,DEADLINE,BUILD_TIME,BUILD_STATE,PICTURE) values (1,'1','超好吃的雞排唷超好吃的雞排唷超好吃的雞排唷超好吃的雞排唷超好吃的雞排唷超好吃的雞排唷超好吃的雞排唷超好吃的雞排唷超好吃的雞排唷超好吃的雞排唷超好吃的雞排唷超好吃的雞排唷','好吃唷',to_date('31-12月-16','DD-MON-RR'),to_date('09-6月 -16','DD-MON-RR'),'live','c4004.jpg');
Insert into SSD.BUILD_ORDER (USER_ID,ORDER_NUMBER,REMARK,ITEM_INFORMATION,DEADLINE,BUILD_TIME,BUILD_STATE,PICTURE) values (1,'12','創立「清心冷飲站」
　　1987年3月8日，趙福全夫妻於台南市南區金華路二段巷弄內，創立「清心冷飲站」，設置一座簡易的吧檯，陳列茶桶、冰櫥、糖罐、杯子等器具，對外販售冷飲、冰品。其中「茶飲」最受消費者的青睞，當日燜煮新鮮且濃厚的熱茶汁，結合清透的衛生冰塊，加入適量的糖水，以調酒杯現場手工沖泡、調製，幻化成風味獨特的茶飲，提供消費者即時、沁涼的外帶飲品。而剛由調酒杯倒入飲用杯中的茶飲，茶湯上層漂浮
首創「烏龍綠茶」
　　茶葉無疑是茶飲的首要元素，趙福全先生經營「清心冷飲站」以來，不僅嚴選優質茶葉以製作茶飲，更多方試茶、品茶、評茶、配茶，精進沖泡、調製技術，參酌顧客回饋意見，以研發更多符合消費者口味的茶飲。1988年6月，成功推出台灣首創「烏龍綠茶」，澄澈的黃褐色茶湯，入口清新芳香、甘醇渾厚，微帶炭燒味，回甘則馥郁而綿長','清新福全',to_date('31-12月-16','DD-MON-RR'),to_date('13-6月 -16','DD-MON-RR'),'live','122203.jpg');
Insert into SSD.BUILD_ORDER (USER_ID,ORDER_NUMBER,REMARK,ITEM_INFORMATION,DEADLINE,BUILD_TIME,BUILD_STATE,PICTURE) values (1,'10','宅配說明﻿
本公司與統一速達黑貓宅急便合作低溫宅配
請在結帳時【備註欄】填寫送達時段、希望到達日(自訂單日起不得小於4天、大於10天)。
訂單成立7~10天內將為您完成出貨；商城系統為保障消費者權益，因此訂單商品不得逾期出貨，敬請見諒。
黑貓提供時段性送達服務，無法在指定精準時間送達(例如：指定AM9:05精準送達)。
配達時段可選擇為：上午(8:00~12:00)、下午(12:00~1','Black As C',to_date('31-12月-16','DD-MON-RR'),to_date('13-6月 -16','DD-MON-RR'),'live','124094.jpg');
Insert into SSD.BUILD_ORDER (USER_ID,ORDER_NUMBER,REMARK,ITEM_INFORMATION,DEADLINE,BUILD_TIME,BUILD_STATE,PICTURE) values (1,'11','創立「清心冷飲站」
　　1987年3月8日，趙福全夫妻於台南市南區金華路二段巷弄內，創立「清心冷飲站」，設置一座簡易的吧檯，陳列茶桶、冰櫥、糖罐、杯子等器具，對外販售冷飲、冰品。其中「茶飲」最受消費者的青睞，當日燜煮新鮮且濃厚的熱茶汁，結合清透的衛生冰塊，加入適量的糖水，以調酒杯現場手工沖泡、調製，幻化成風味獨特的茶飲，提供消費者即時、沁涼的外帶飲品。而剛由調酒杯倒入飲用杯中的茶飲，茶湯上層漂浮
首創「烏龍綠茶」
　　茶葉無疑是茶飲的首要元素，趙福全先生經營「清心冷飲站」以來，不僅嚴選優質茶葉以製作茶飲，更多方試茶、品茶、評茶、配茶，精進沖泡、調製技術，參酌顧客回饋意見，以研發更多符合消費者口味的茶飲。1988年6月，成功推出台灣首創「烏龍綠茶」，澄澈的黃褐色茶湯，入口清新芳香、甘醇渾厚，微帶炭燒味，回甘則馥郁而綿長','清新福全',to_date('31-12月-16','DD-MON-RR'),to_date('13-6月 -16','DD-MON-RR'),'live','358378.jpg');
REM INSERTING into SSD.CASH_LOG
SET DEFINE OFF;
Insert into SSD.CASH_LOG (USER_ID,LOG_NUMBER,TIME,MONEY) values (2,'2',to_date('08-6月 -16','DD-MON-RR'),4564);
Insert into SSD.CASH_LOG (USER_ID,LOG_NUMBER,TIME,MONEY) values (1,'1',to_date('09-6月 -16','DD-MON-RR'),500);
REM INSERTING into SSD.ITEM_INFORMATION
SET DEFINE OFF;
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'焦糖香蕉巧克力蛋糕','5','2',500,200,250,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'Black As Chocolate','6','2',500,200,199,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'炭烤戰斧豬','7','3',300,20,599,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'3.5吋經典巧克力蛋糕','3','2',500,200,299,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'3.5吋黑嘉侖草莓巧克力蛋糕','4','2',500,200,350,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'低溫烹調牛小排茶','8','3',300,20,699,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'酥炸柳葉魚野菇燉飯','9','3',300,20,299,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'野菇雞肉義大利麵','10','3',300,20,99,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'脆皮雞排','11','4',799,30,50,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'脆皮雞塊','12','4',799,30,40,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'脆皮魷魚','13','4',799,30,65,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'脆皮薯條','14','4',799,30,25,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'義大利麵','20','6',50,20,120,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'咖啡','21','7',50,20,null,'5/10','3/7/10','b/m/s',50,40,30);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'3.5吋經典巧克力蛋糕','28','9',200,200,299,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'百香果綠','17','5',150,30,null,'0/3/5/7','0/10','b/m/s',55,45,35);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'賣香三兄弟','18','5',150,30,null,'0/5/7/10','0/10','b/m/s',10,5,3);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'3.5吋黑嘉侖草莓巧克力蛋糕','29','9',200,200,350,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'烏龍茶','15','5',150,30,null,'5/7/10','0/5','b/s',35,30,25);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'奶綠','16','5',150,30,null,'0/5/7/10','0/10','b/m/s',35,30,25);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'焦糖香蕉巧克力蛋糕','26','9',200,200,250,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'Black As Chocolate','27','9',200,200,199,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'焦糖香蕉巧克力蛋糕','32','10',200,200,250,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'3.5吋經典巧克力蛋糕','30','10',200,200,299,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'3.5吋黑嘉侖草莓巧克力蛋糕','31','10',200,200,350,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'Black As Chocolate','33','10',200,200,199,null,null,null,null,null,null);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'烏龍茶','34','11',150,30,null,'0/7/10','0/7/10','b/m/s',35,30,25);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'百香果綠','35','11',150,30,null,'5/7/10','0/3/10','b',55,45,35);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'奶綠','36','11',150,30,null,'3/5/10','0/3/10','b/m/s',35,30,25);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'賣香三兄弟','37','11',150,30,null,'3/5/10','0/3/10','b/m/s',10,10,10);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'百香果綠','38','12',150,30,null,'10','10','b',55,45,35);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'賣香三兄弟','39','12',150,30,null,'10','0/3/5/7/10','b',10,10,10);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'烏龍茶','40','12',150,30,null,'10','10','b',35,30,25);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'奶綠','41','12',150,30,null,'10','10','b',35,30,25);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'烏龍茶','24','8',150,30,null,'10','3/5/10','b',35,30,25);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'百香果綠','22','8',150,30,null,'10','10','b',55,45,35);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'奶綠','25','8',150,30,null,'10','3/5/10','b',35,30,25);
Insert into SSD.ITEM_INFORMATION (USER_ID,NAME,ITEM_NUMBER,ORDER_NUMBER,MAX,MIN,MONEY,SUGER,ICE,"SIZE",BIG_PRICE,MID_PRICE,SMALL_PRICE) values (1,'賣香三兄弟','23','8',150,30,null,'10','10','b',10,10,10);
REM INSERTING into SSD.JOIN_ORDER
SET DEFINE OFF;
Insert into SSD.JOIN_ORDER (JOIN_LOG,ORDER_NUMBER,ITEM_NUMBER,COUNT,JOIN_TIME,GET,USER_ID,MONEY,"SIZE",SUGER,ICE) values ('5','11','37',1,to_date('08-8月 -16','DD-MON-RR'),0,2,10,'b','10','10');
Insert into SSD.JOIN_ORDER (JOIN_LOG,ORDER_NUMBER,ITEM_NUMBER,COUNT,JOIN_TIME,GET,USER_ID,MONEY,"SIZE",SUGER,ICE) values ('6','11','36',1,to_date('08-8月 -16','DD-MON-RR'),0,2,35,'b','10','10');
Insert into SSD.JOIN_ORDER (JOIN_LOG,ORDER_NUMBER,ITEM_NUMBER,COUNT,JOIN_TIME,GET,USER_ID,MONEY,"SIZE",SUGER,ICE) values ('3','12','38',1,to_date('08-8月 -16','DD-MON-RR'),0,2,55,'b','10','10');
Insert into SSD.JOIN_ORDER (JOIN_LOG,ORDER_NUMBER,ITEM_NUMBER,COUNT,JOIN_TIME,GET,USER_ID,MONEY,"SIZE",SUGER,ICE) values ('4','11','34',1,to_date('08-8月 -16','DD-MON-RR'),0,2,35,'b','10','10');
Insert into SSD.JOIN_ORDER (JOIN_LOG,ORDER_NUMBER,ITEM_NUMBER,COUNT,JOIN_TIME,GET,USER_ID,MONEY,"SIZE",SUGER,ICE) values ('7','11','35',1,to_date('08-8月 -16','DD-MON-RR'),0,2,55,'b','10','10');
Insert into SSD.JOIN_ORDER (JOIN_LOG,ORDER_NUMBER,ITEM_NUMBER,COUNT,JOIN_TIME,GET,USER_ID,MONEY,"SIZE",SUGER,ICE) values ('10','11','34',1,to_date('08-8月 -16','DD-MON-RR'),0,2,35,'b','10','10');
Insert into SSD.JOIN_ORDER (JOIN_LOG,ORDER_NUMBER,ITEM_NUMBER,COUNT,JOIN_TIME,GET,USER_ID,MONEY,"SIZE",SUGER,ICE) values ('11','11','37',1,to_date('08-8月 -16','DD-MON-RR'),0,2,10,'b','10','10');
Insert into SSD.JOIN_ORDER (JOIN_LOG,ORDER_NUMBER,ITEM_NUMBER,COUNT,JOIN_TIME,GET,USER_ID,MONEY,"SIZE",SUGER,ICE) values ('12','11','36',1,to_date('08-8月 -16','DD-MON-RR'),0,2,35,'b','10','10');
Insert into SSD.JOIN_ORDER (JOIN_LOG,ORDER_NUMBER,ITEM_NUMBER,COUNT,JOIN_TIME,GET,USER_ID,MONEY,"SIZE",SUGER,ICE) values ('13','11','35',1,to_date('08-8月 -16','DD-MON-RR'),0,2,55,'b','10','10');
Insert into SSD.JOIN_ORDER (JOIN_LOG,ORDER_NUMBER,ITEM_NUMBER,COUNT,JOIN_TIME,GET,USER_ID,MONEY,"SIZE",SUGER,ICE) values ('9','12','38',1,to_date('08-8月 -16','DD-MON-RR'),0,2,55,'b','10','10');
REM INSERTING into SSD.USER_DATA
SET DEFINE OFF;
Insert into SSD.USER_DATA (USER_ID,ACCOUNT,PASSWORD,NAME,PHONE,EMAIL,MONEY) values (4,'qqqqqq','qqqqqq','qqqqq','12345567','2113@edwedw',0);
Insert into SSD.USER_DATA (USER_ID,ACCOUNT,PASSWORD,NAME,PHONE,EMAIL,MONEY) values (5,'abc111','1234567','jijijih','ijiji','jnjn',0);
Insert into SSD.USER_DATA (USER_ID,ACCOUNT,PASSWORD,NAME,PHONE,EMAIL,MONEY) values (0,'root','root','root',null,null,null);
Insert into SSD.USER_DATA (USER_ID,ACCOUNT,PASSWORD,NAME,PHONE,EMAIL,MONEY) values (3,'user123','user123','我超帥','02235444545','kuhsd@gmail.com',6664);
Insert into SSD.USER_DATA (USER_ID,ACCOUNT,PASSWORD,NAME,PHONE,EMAIL,MONEY) values (1,'hrhrhr','hrhrhr','hrhrhr','09123456789','515sw@51151.wqewq',500);
Insert into SSD.USER_DATA (USER_ID,ACCOUNT,PASSWORD,NAME,PHONE,EMAIL,MONEY) values (2,'abc123','abc123','超帥的','09123456789','wsx5555@eeeee.qqqq',90);
--------------------------------------------------------
--  DDL for Index SYS_C009976
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSD"."SYS_C009976" ON "SSD"."BUILD_ORDER" ("ORDER_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009974
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSD"."SYS_C009974" ON "SSD"."CASH_LOG" ("LOG_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009978
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSD"."SYS_C009978" ON "SSD"."ITEM_INFORMATION" ("ITEM_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009980
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSD"."SYS_C009980" ON "SSD"."JOIN_ORDER" ("JOIN_LOG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009972
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSD"."SYS_C009972" ON "SSD"."USER_DATA" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BUILD_ORDER
--------------------------------------------------------

  ALTER TABLE "SSD"."BUILD_ORDER" ADD PRIMARY KEY ("ORDER_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SSD"."BUILD_ORDER" MODIFY ("ORDER_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SSD"."BUILD_ORDER" MODIFY ("ITEM_INFORMATION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CASH_LOG
--------------------------------------------------------

  ALTER TABLE "SSD"."CASH_LOG" ADD PRIMARY KEY ("LOG_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SSD"."CASH_LOG" MODIFY ("LOG_NUMBER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ITEM_INFORMATION
--------------------------------------------------------

  ALTER TABLE "SSD"."ITEM_INFORMATION" ADD PRIMARY KEY ("ITEM_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SSD"."ITEM_INFORMATION" MODIFY ("ITEM_NUMBER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JOIN_ORDER
--------------------------------------------------------

  ALTER TABLE "SSD"."JOIN_ORDER" ADD PRIMARY KEY ("JOIN_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SSD"."JOIN_ORDER" MODIFY ("JOIN_LOG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_DATA
--------------------------------------------------------

  ALTER TABLE "SSD"."USER_DATA" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SSD"."USER_DATA" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BUILD_ORDER
--------------------------------------------------------

  ALTER TABLE "SSD"."BUILD_ORDER" ADD CONSTRAINT "BUILD_ORDER_USER_DATA_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "SSD"."USER_DATA" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CASH_LOG
--------------------------------------------------------

  ALTER TABLE "SSD"."CASH_LOG" ADD CONSTRAINT "CASH_LOG_USER_DATA_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "SSD"."USER_DATA" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ITEM_INFORMATION
--------------------------------------------------------

  ALTER TABLE "SSD"."ITEM_INFORMATION" ADD CONSTRAINT "ITEM_INFORMATION_BUILD_OR_FK1" FOREIGN KEY ("ORDER_NUMBER")
	  REFERENCES "SSD"."BUILD_ORDER" ("ORDER_NUMBER") ENABLE;
  ALTER TABLE "SSD"."ITEM_INFORMATION" ADD CONSTRAINT "ITEM_INFORMATION_USER_DAT_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "SSD"."USER_DATA" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JOIN_ORDER
--------------------------------------------------------

  ALTER TABLE "SSD"."JOIN_ORDER" ADD CONSTRAINT "JOIN_ORDER_BUILD_ORDER_FK1" FOREIGN KEY ("ORDER_NUMBER")
	  REFERENCES "SSD"."BUILD_ORDER" ("ORDER_NUMBER") ENABLE;
  ALTER TABLE "SSD"."JOIN_ORDER" ADD CONSTRAINT "JOIN_ORDER_ITEM_INFORMATI_FK1" FOREIGN KEY ("ITEM_NUMBER")
	  REFERENCES "SSD"."ITEM_INFORMATION" ("ITEM_NUMBER") ENABLE;
  ALTER TABLE "SSD"."JOIN_ORDER" ADD CONSTRAINT "JOIN_ORDER_USER_DATA_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "SSD"."USER_DATA" ("USER_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRI_AUTO_INCREMENT_JOIN_ORDER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SSD"."TRI_AUTO_INCREMENT_JOIN_ORDER" 
    BEFORE INSERT ON JOIN_ORDER
    FOR EACH ROW
    BEGIN
        SELECT seq_JOIN_ORDER.NEXTVAL INTO :NEW.JOIN_LOG FROM DUAL;
    END;
/
ALTER TRIGGER "SSD"."TRI_AUTO_INCREMENT_JOIN_ORDER" ENABLE;
